const { EmbedBuilder } = require('discord.js');

module.exports = {
  createPromptEmbed: function (
    prompt,
    thumbnailLink,
    imageLink,
    username,
    discriminator
  ) {
    console.log('creating embedding here');
    const embed = new EmbedBuilder()
      .setColor(0x0099ff)
      .setTitle('Prompt: ' + prompt)
      .setThumbnail(thumbnailLink)
      .setImage(imageLink)
      .setTimestamp()
      .setFooter({
        text: 'Generated by: ' + username + '#' + discriminator,
        iconURL: imageLink,
      });

    return embed;
  },
};
